// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJuKzeObxUmsvLKAMn6qb2w65DBNrwcW4',
    appId: '1:384550215253:web:efab2f72f6ff6f3b677edc',
    messagingSenderId: '384550215253',
    projectId: 'sudokuminglebyminglebytes',
    authDomain: 'sudokuminglebyminglebytes.firebaseapp.com',
    storageBucket: 'sudokuminglebyminglebytes.appspot.com',
    measurementId: 'G-TPJ8QD14JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeme0qCPz049M0uoWDlpiSIMr9aha8BMQ',
    appId: '1:384550215253:android:91c95f629af1c7fa677edc',
    messagingSenderId: '384550215253',
    projectId: 'sudokuminglebyminglebytes',
    storageBucket: 'sudokuminglebyminglebytes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB2eSdGGeRp_i74iZTTi5ATzvhiJskkO0',
    appId: '1:384550215253:ios:1cbd43474c44dbfb677edc',
    messagingSenderId: '384550215253',
    projectId: 'sudokuminglebyminglebytes',
    storageBucket: 'sudokuminglebyminglebytes.appspot.com',
    iosClientId: '384550215253-577in4mu57v3l0uesphujfjh73tashia.apps.googleusercontent.com',
    iosBundleId: 'com.minglebytes.sudokumingle',
  );
}
